if(has_include_ROOT)
    include(CMakePrintHelpers)
    set(has_include_INCLUDE_DIRS ${has_include_ROOT}/include)
    set(has_include_LIBRARIES)
    if(USE_EXTERNAL_BOOST)
      find_package(Boost)
      cmake_print_variables(Boost_FOUND)
      if(Boost_FOUND)
        list(APPEND has_include_LIBRARIES Boost::headers)
    endif()
    endif()
    set(has_include_FOUND TRUE)
    if(NOT TARGET has_include::has_include)
      add_library(has_include_header_only INTERFACE)
      add_library(has_include::has_include ALIAS has_include_header_only)
      list(APPEND has_include_LIBRARIES has_include::has_include)
      set_target_properties(has_include_header_only PROPERTIES
        INTERFACE_INCLUDE_DIRECTORIES "${has_include_INCLUDE_DIRS}"
        INTERFACE_LINK_LIBRARIES "${has_include_LIBRARIES}"
      )
    endif()
    cmake_print_variables(has_include_LIBRARIES)
    cmake_print_variables(has_include_INCLUDE_DIRS)
endif()
